version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app:cached"
      - "bundle:/usr/local/bundle:delegated"
    ports:
      - "4567:4567"
    command: ["bundle", "exec", "middleman", "server", "--bind-address", "0.0.0.0"]
volumes:
  bundle:
    driver: local
